definitions:
  dto.LoginDto:
    properties:
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  dto.NewUserDto:
    properties:
      password:
        minLength: 6
        type: string
      role:
        enum:
        - admin
        - user
        - superadmin
        type: string
      username:
        maxLength: 100
        minLength: 2
        type: string
      uuid:
        type: string
    required:
    - password
    - role
    - username
    type: object
  dto.TokenDto:
    properties:
      accessToken:
        type: string
    type: object
  dto.UserDto:
    properties:
      policeToken:
        type: string
      role:
        type: string
      username:
        type: string
      uuid:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns access and refresh tokens
      parameters:
      - description: Login credentials
        in: body
        name: loginDto
        required: true
        schema:
          $ref: '#/definitions/dto.LoginDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TokenDto'
      summary: User login
      tags:
      - auth
  /auth/logout:
    post:
      description: Generates a new access token using a valid refresh token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TokenDto'
      summary: Refresh Access Token
      tags:
      - auth
  /auth/refresh:
    post:
      description: Generates a new access token using a valid refresh token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TokenDto'
      summary: Refresh Access Token
      tags:
      - auth
  /info:
    get:
      description: return information about the server build, version, etc ...
      produces:
      - application/json
      responses:
        "200":
          description: Information about server
          schema:
            type: struct
      summary: Get server info
      tags:
      - info
  /tunnel:
    get:
      description: returns a list of all tunnels
      produces:
      - application/json
      responses:
        "200":
          description: List of tunnels
          schema:
            type: struct
      summary: Get a list of all tunnels
      tags:
      - tunnel
    post:
      description: creates a new tunnel with given name and returns it
      parameters:
      - description: tunnel name
        in: body
        name: name
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Newly created tunnel
          schema:
            type: struct
      summary: creates a new tunnel
      tags:
      - tunnel
  /tunnel/{id}:
    delete:
      description: returns a list of all tunnels
      parameters:
      - description: tunnel id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Tunnel deleted
      summary: Get a list of all tunnels
      tags:
      - tunnel
  /user:
    post:
      parameters:
      - description: Data for new user
        in: body
        name: model
        required: true
        schema:
          $ref: '#/definitions/dto.NewUserDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.UserDto'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Create new user
      tags:
      - user
  /user/{uuid}:
    delete:
      description: delete a user with uuid
      parameters:
      - description: user uuid
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: delete user with uuid
      tags:
      - user
    get:
      description: get a user with uuid
      parameters:
      - description: user uuid
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserDto'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: get user with uuid
      tags:
      - user
    put:
      parameters:
      - description: uuid of user to be updated
        in: path
        name: uuid
        required: true
        type: string
      - description: Data for updating user
        in: body
        name: model
        required: true
        schema:
          $ref: '#/definitions/dto.UserDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserDto'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Update user with new dat
      tags:
      - user
  /user/all-users:
    get:
      description: Fetches all users for superadmin
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.UserDto'
            type: array
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: Get all users for superadmin
      tags:
      - user
  /user/my-data:
    get:
      description: Fetches the currently logged-in user's data based on the JWT token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserDto'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get logged-in user data
      tags:
      - user
  /user/oib/{oib}:
    get:
      description: get a user with oib
      parameters:
      - description: user oib
        in: path
        name: oib
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserDto'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: get user with oib
      tags:
      - user
  /user/search:
    get:
      description: Performs a fuzzy search for users by first name, last name, or
        full name with similarity matching
      parameters:
      - description: Search query
        in: query
        name: query
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.UserDto'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Search users by name
      tags:
      - user
swagger: "2.0"
